"use client";
import{useCallback,useEffect,useState}from"react";import{CalendarClock,Edit3,Megaphone,Plus,Trash2,X}from"lucide-react";import{Panel}from"@/components/ui/Panel";import{useAutoRefresh}from"@/lib/client/use-auto-refresh";
type Change={id:string;version:string;title:string;body:string;publishedAt:string};type Announcement={id:string;title:string;body:string;type:string;isActive:boolean;startsAt?:string|null;endsAt?:string|null};type Archive={id:string;source:string;archiveDate:string;sizeBytes:number};type Editor={kind:"change"|"announcement";item?:Change|Announcement};
export function ContentManager(){
  const[changes,setChanges]=useState<Change[]>([]),[announcements,setAnnouncements]=useState<Announcement[]>([]),[archives,setArchives]=useState<Archive[]>([]),[error,setError]=useState(""),[editor,setEditor]=useState<Editor|null>(null),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const[c,a,r]=await Promise.all([fetch("/api/changelog",{cache:"no-store"}),fetch("/api/announcements",{cache:"no-store"}),fetch("/api/archives",{cache:"no-store"})]);if(c.ok)setChanges(await c.json());if(a.ok)setAnnouncements(await a.json());if(r.ok)setArchives(await r.json())},[]);useEffect(()=>{void load()},[load]);useAutoRefresh(load);
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;setBusy(true);setError("");const raw=Object.fromEntries(new FormData(e.currentTarget).entries())as Record<string,string>;const isAnnouncement=editor.kind==="announcement";const body=isAnnouncement?{...raw,isActive:raw.isActive==="true",startsAt:raw.startsAt||null,endsAt:raw.endsAt||null}:{...raw,publishedAt:raw.publishedAt||undefined};const endpoint=isAnnouncement?"/api/announcements":"/api/changelog",method=editor.item?"PATCH":"POST";const response=await fetch(endpoint,{method,headers:{"content-type":"application/json"},body:JSON.stringify(editor.item?{...body,id:editor.item.id}:body)});setBusy(false);if(!response.ok)return setError((await response.json()).error);setEditor(null);await load()}
  async function remove(kind:Editor["kind"],item:Change|Announcement){if(!confirm(`Delete “${item.title}”? This cannot be undone.`))return;const response=await fetch(kind==="change"?"/api/changelog":"/api/announcements",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})});if(!response.ok)setError((await response.json()).error);else await load()}
  return <div className="owner-content-stack"><Panel className="content-management-panel"><div className="panel-header"><div><h2>Changelog</h2><p>Product updates shown in What’s new.</p></div><button className="secondary-button compact" onClick={()=>setEditor({kind:"change"})}><Plus size={16}/>New update</button></div><div className="managed-list">{changes.map(item=><article key={item.id}><div className="managed-icon"><CalendarClock size={18}/></div><div><small>v{item.version} · {new Date(item.publishedAt).toLocaleDateString()}</small><strong>{item.title}</strong><p>{item.body}</p></div><div className="managed-actions"><button className="icon-button" onClick={()=>setEditor({kind:"change",item})} aria-label={`Edit ${item.title}`}><Edit3 size={16}/></button><button className="icon-button danger-icon" onClick={()=>void remove("change",item)} aria-label={`Delete ${item.title}`}><Trash2 size={16}/></button></div></article>)}{!changes.length?<div className="empty-state">No product updates yet.</div>:null}</div></Panel>
  <Panel className="content-management-panel"><div className="panel-header"><div><h2>Announcements</h2><p>Time-sensitive messages displayed on user dashboards.</p></div><button className="secondary-button compact" onClick={()=>setEditor({kind:"announcement"})}><Plus size={16}/>New announcement</button></div><div className="managed-list">{announcements.map(item=><article key={item.id}><div className={`managed-icon is-${item.type}`}><Megaphone size={18}/></div><div><small>{item.type} · {item.isActive?"Active":"Paused"}</small><strong>{item.title}</strong><p>{item.body}</p></div><div className="managed-actions"><button className="icon-button" onClick={()=>setEditor({kind:"announcement",item})} aria-label={`Edit ${item.title}`}><Edit3 size={16}/></button><button className="icon-button danger-icon" onClick={()=>void remove("announcement",item)} aria-label={`Delete ${item.title}`}><Trash2 size={16}/></button></div></article>)}{!announcements.length?<div className="empty-state">No announcements yet.</div>:null}</div></Panel>
  <Panel className="archive-panel"><div className="panel-header"><div><h2>Message archives</h2><p>Encrypted exports created by the archive schedule.</p></div></div>{archives.length?<div className="archive-list">{archives.map(x=><a key={x.id} href={`/api/archives?id=${x.id}`}><strong>{x.source}</strong><span>{new Date(x.archiveDate).toLocaleDateString()} · {formatBytes(x.sizeBytes)}</span></a>)}</div>:<div className="empty-state">No archives created yet.</div>}</Panel>{error?<p className="form-error">{error}</p>:null}
  {editor?<EditorModal editor={editor} busy={busy} onClose={()=>setEditor(null)} onSave={save}/>:null}</div>
}
function EditorModal({editor,busy,onClose,onSave}:{editor:Editor;busy:boolean;onClose:()=>void;onSave:(e:React.FormEvent<HTMLFormElement>)=>void}){const change=editor.kind==="change"?editor.item as Change|undefined:undefined,announcement=editor.kind==="announcement"?editor.item as Announcement|undefined:undefined;return <div className="modal-backdrop"><section className="resource-modal content-editor" role="dialog" aria-modal="true" aria-labelledby="content-editor-title"><div className="modal-heading"><div><h2 id="content-editor-title">{editor.item?"Edit":"Create"} {editor.kind==="change"?"changelog update":"announcement"}</h2><p>Changes are reflected across the platform immediately.</p></div><button className="icon-button" onClick={onClose} aria-label="Close"><X/></button></div><form className="resource-form single" onSubmit={onSave}>{editor.kind==="change"?<><label>Version<input name="version" defaultValue={change?.version} required/></label><label>Title<input name="title" defaultValue={change?.title} required/></label><label>Update details<textarea name="body" defaultValue={change?.body} required/></label><label>Publish date<input name="publishedAt" type="datetime-local" defaultValue={toLocalDate(change?.publishedAt)}/></label></>:<><label>Title<input name="title" defaultValue={announcement?.title} required/></label><label>Message<textarea name="body" defaultValue={announcement?.body} required/></label><div className="form-split"><label>Style<select name="type" defaultValue={announcement?.type||"info"}><option value="info">Information</option><option value="success">Success</option><option value="warning">Warning</option></select></label><label>Status<select name="isActive" defaultValue={String(announcement?.isActive??true)}><option value="true">Active</option><option value="false">Paused</option></select></label></div><div className="form-split"><label>Starts at<input name="startsAt" type="datetime-local" defaultValue={toLocalDate(announcement?.startsAt)}/></label><label>Ends at<input name="endsAt" type="datetime-local" defaultValue={toLocalDate(announcement?.endsAt)}/></label></div></>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Saving…":"Save"}</button></div></form></section></div>}
function toLocalDate(value?:string|null){if(!value)return"";const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(1)} MB`}
