import { createHash } from "node:crypto";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { clientIp,rateLimit } from "@/lib/rate-limit";
import { jsonError,parseJson,sameOrigin } from "@/lib/api";
import { notifyUser } from "@/lib/notifications";
const tokenSchema=z.string().min(40).max(60).regex(/^[A-Za-z0-9_-]+$/),replySchema=z.object({body:z.string().trim().min(2).max(5000)});const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
async function reportFor(token:string){return prisma.report.findUnique({where:{guestTokenHash:hashToken(token)},include:{replies:{include:{user:{select:{name:true,role:true}}},orderBy:{createdAt:"asc"}}}})}
export async function GET(request:Request,{params}:{params:Promise<{token:string}>}){if(!rateLimit(`public-ticket:${clientIp(request)}`,30,60_000).allowed)return jsonError("Too many requests",429);const parsed=tokenSchema.safeParse((await params).token);if(!parsed.success)return jsonError("Ticket not found",404);const report=await reportFor(parsed.data);if(!report)return jsonError("Ticket not found",404);return Response.json({id:report.id,reference:report.id.slice(0,8).toUpperCase(),contactName:report.contactName,subject:report.subject,body:report.body,status:report.status,createdAt:report.createdAt,replies:report.replies.map(reply=>({id:reply.id,body:reply.body,createdAt:reply.createdAt,author:reply.user?.name||reply.user?.role||reply.guestName||report.contactName,staff:Boolean(reply.user)}))})}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){if(!sameOrigin(request))return jsonError("Invalid origin",403);if(!rateLimit(`public-ticket-reply:${clientIp(request)}`,8,60_000).allowed)return jsonError("Please wait before replying again",429);const token=tokenSchema.safeParse((await params).token),body=replySchema.safeParse(await parseJson(request));if(!token.success||!body.success)return jsonError("Invalid reply",422);const report=await reportFor(token.data);if(!report)return jsonError("Ticket not found",404);if(report.status==="closed")return jsonError("This ticket is closed and cannot receive more replies",409);const reply=await prisma.reportReply.create({data:{reportId:report.id,body:body.data.body,guestName:report.contactName,guestEmail:report.contactEmail}});if(report.status==="resolved")await prisma.report.update({where:{id:report.id},data:{status:"open"}});const staff=await prisma.user.findMany({where:{role:{in:["owner","admin","moderator"]},status:"active"},select:{id:true}});await Promise.all(staff.map(user=>notifyUser({userId:user.id,type:"support_user_reply",title:`External user replied: ${report.subject}`,body:body.data.body.slice(0,180),metadata:{href:`/admin/reports?ticket=${report.id}`,reportId:report.id}})));return Response.json({id:reply.id},{status:201})}
