"use client";
import{useCallback,useEffect,useMemo,useState}from"react";import{Edit3,KeyRound,Search,Trash2,X}from"lucide-react";import{Panel}from"@/components/ui/Panel";import{useAutoRefresh}from"@/lib/client/use-auto-refresh";
type User={id:string;name?:string;username:string;email:string;role:string;status:string;forcePasswordReset:boolean;lastLoginAt?:string;createdAt?:string};
export function UserManager(){
  const[users,setUsers]=useState<User[]>([]),[actor,setActor]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("all"),[resetUser,setResetUser]=useState<User|null>(null),[editUser,setEditUser]=useState<User|null>(null),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const[r,me]=await Promise.all([fetch("/api/admin/users",{cache:"no-store"}),fetch("/api/me",{cache:"no-store"})]);const body=await r.json();if(r.ok)setUsers(body);else setError(body.error);if(me.ok)setActor((await me.json()).role)},[]);useEffect(()=>{void load()},[load]);useAutoRefresh(load);
  const filtered=useMemo(()=>users.filter(user=>(statusFilter==="all"||user.status===statusFilter)&&`${user.name} ${user.username} ${user.email}`.toLowerCase().includes(query.toLowerCase())),[users,query,statusFilter]);
  async function update(userId:string,data:object){setBusy(true);setError("");const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,...data})});setBusy(false);if(!response.ok){setError((await response.json()).error);return false}await load();return true}
  async function remove(userId:string){if(!confirm("Delete this user and all owned data? This cannot be undone."))return;const response=await fetch("/api/admin/users",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({userId})});if(!response.ok)setError((await response.json()).error);else await load()}
  async function reset(){if(!resetUser)return;if(await update(resetUser.id,{newPassword:password,forcePasswordReset:true})){setResetUser(null);setPassword("")}}
  async function saveIdentity(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editUser)return;const values=Object.fromEntries(new FormData(e.currentTarget).entries());if(await update(editUser.id,values))setEditUser(null)}
  return <><header className="workspace-header"><div><h1>Users</h1><p>Manage identity, roles, account access and recovery from one place.</p></div><span className="record-count">{filtered.length} users</span></header><div className="management-toolbar"><label className="admin-search"><Search size={17}/><input aria-label="Search users" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, username or email"/></label><select aria-label="Filter by status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select></div>{error?<p className="form-error" role="alert">{error}</p>:null}<Panel className="table-panel user-table-wrap"><table className="admin-user-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Joined / last login</th>{actor!=="moderator"?<th>Actions</th>:null}</tr></thead><tbody>{filtered.map(user=><tr key={user.id}><td><div className="user-identity"><span className="avatar">{(user.name||user.username).slice(0,2).toUpperCase()}</span><span><strong>{user.name||"Unnamed user"}</strong><small>@{user.username} · {user.email}</small>{user.forcePasswordReset?<em className="account-flag">Password reset required</em>:null}</span></div></td><td>{actor!=="moderator"?<select aria-label={`Role for ${user.username}`} value={user.role} onChange={e=>void update(user.id,{role:e.target.value})}>{["user","moderator","admin","owner"].map(value=><option key={value}>{value}</option>)}</select>:<span className="role-chip">{user.role}</span>}</td><td><select aria-label={`Status for ${user.username}`} value={user.status} onChange={e=>void update(user.id,{status:e.target.value})}>{(actor==="moderator"?["active","suspended"]:["active","suspended","banned"]).map(value=><option key={value}>{value}</option>)}</select></td><td><span className="table-date"><strong>{user.createdAt?new Date(user.createdAt).toLocaleDateString():"—"}</strong><small>{user.lastLoginAt?`Last seen ${new Date(user.lastLoginAt).toLocaleDateString()}`:"Never signed in"}</small></span></td>{actor!=="moderator"?<td><div className="row-actions"><button className="secondary-button icon-action" onClick={()=>setEditUser(user)}><Edit3 size={15}/>Edit</button><button className="secondary-button icon-action" onClick={()=>setResetUser(user)}><KeyRound size={15}/>Reset</button><button className="danger-button square-action" onClick={()=>void remove(user.id)} aria-label={`Delete ${user.username}`}><Trash2 size={16}/></button></div></td>:null}</tr>)}{!filtered.length?<tr><td colSpan={5}><div className="empty-state">No users match this view.</div></td></tr>:null}</tbody></table></Panel>
  {editUser?<div className="modal-backdrop"><section className="resource-modal" role="dialog" aria-modal="true" aria-labelledby="edit-user-title"><div className="modal-heading"><div><h2 id="edit-user-title">Edit user identity</h2><p>Update the account details used across the platform.</p></div><button className="icon-button" onClick={()=>setEditUser(null)} aria-label="Close"><X/></button></div><form className="resource-form single" onSubmit={saveIdentity}><label>Full name<input name="name" defaultValue={editUser.name||""} required/></label><label>Username<input name="username" defaultValue={editUser.username} required/></label><label>Email address<input name="email" type="email" defaultValue={editUser.email} required/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditUser(null)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Saving…":"Save user"}</button></div></form></section></div>:null}
  {resetUser?<div className="modal-backdrop"><section className="resource-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><div className="modal-heading"><div><h2 id="reset-title">Reset @{resetUser.username}’s password</h2><p>Create a temporary password and require a change on next sign-in.</p></div><button className="icon-button" onClick={()=>setResetUser(null)} aria-label="Close"><X/></button></div><label className="modal-field">Temporary password<input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 10 characters"/></label><div className="modal-actions"><button className="secondary-button" onClick={()=>setResetUser(null)}>Cancel</button><button className="primary-button" disabled={busy||password.length<10} onClick={()=>void reset()}>{busy?"Resetting…":"Reset password"}</button></div></section></div>:null}</>}
