"use client";
import Image from"next/image";import{ImageOff,Trash2,UploadCloud}from"lucide-react";import{useEffect,useState}from"react";
type SiteField={key:string;label:string;type:"text"|"time";hint?:string}|{key:string;label:string;type:"select";options:readonly(readonly[string,string])[];hint?:string};
const fields:readonly SiteField[]=[{key:"site_name",label:"Site name",type:"text",hint:"Used across browser titles and emails, even when hidden beside the logo."},{key:"site_brand_display",label:"Brand display",type:"select",options:[["logo","Logo only"],["logo_name","Logo + site name"]],hint:"Applied when a custom logo is uploaded."},{key:"registration_open",label:"Registration",type:"select",options:[["true","Open"],["false","Closed"]]},{key:"site_mode",label:"Site availability",type:"select",options:[["live","Live"],["maintenance","Maintenance"],["closed","Closed"]]},{key:"archive_time",label:"Archive time",type:"time",hint:"Daily time used by the message archive job."}];
export function SettingsForm(){
  const[values,setValues]=useState<Record<string,string>>({}),[msg,setMsg]=useState(""),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/settings",{cache:"no-store"}).then(r=>r.json()).then(v=>setValues({...v,site_name:v.site_name||"Pigeon",site_brand_display:v.site_brand_display||"logo",registration_open:v.registration_open??"true",site_mode:v.site_mode??"live",archive_time:v.archive_time??"00:00"}))},[]);
  function announce(message:string){setMsg(message);window.dispatchEvent(new Event("pigeon:site-updated"))}
  async function upload(file?:File){if(!file)return;setUploading(true);setMsg("");const data=new FormData();data.set("file",file);const r=await fetch("/api/uploads/logo",{method:"POST",body:data}),body=await r.json();if(r.ok){setValues(v=>({...v,site_logo_url:body.url}));announce("Logo uploaded and activated.")}else setMsg(body.error);setUploading(false)}
  async function removeLogo(){if(!confirm("Remove the current site logo? The site name will be used as the brand instead."))return;setUploading(true);const r=await fetch("/api/uploads/logo",{method:"DELETE"});if(r.ok){setValues(v=>({...v,site_logo_url:""}));announce("Logo removed. The site name is now the brand.")}else setMsg((await r.json()).error);setUploading(false)}
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg("");const payload=Object.fromEntries(Object.entries(values).filter(([key])=>key!=="site_logo_url"));const r=await fetch("/api/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok)announce("Site controls saved.");else setMsg((await r.json()).error??"Unable to save these settings");setSaving(false)}
  return <form className="site-settings-form" onSubmit={submit}><section className="logo-uploader"><div className="logo-preview">{values.site_logo_url?<Image src={values.site_logo_url} alt="Current site logo" width={78} height={78} unoptimized/>:<span className="logo-name-preview">{values.site_name||"Pigeon"}</span>}</div><div className="logo-upload-copy"><strong>{values.site_logo_url?"Custom site logo":"Using the site name"}</strong><p>{values.site_logo_url?"This image appears throughout the platform.":"Upload a logo if you want one. No default image will be shown."}</p><div className="logo-actions"><label className="secondary-button"><UploadCloud size={17}/>{uploading?"Working…":"Upload logo"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])} disabled={uploading}/></label>{values.site_logo_url?<button type="button" className="danger-button" onClick={()=>void removeLogo()} disabled={uploading}><Trash2 size={16}/>Remove logo</button>:<span className="logo-empty-hint"><ImageOff size={16}/>PNG, JPG or WebP · 2 MB max</span>}</div></div></section><div className="site-fields">{fields.map(field=><label key={field.key}><span>{field.label}</span>{field.type==="select"?<select value={values[field.key]??field.options[0][0]} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))}>{field.options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:<input type={field.type??"text"} value={values[field.key]??""} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))} required/>}{"hint"in field&&field.hint?<small>{field.hint}</small>:null}</label>)}</div><div className="site-form-footer"><p className="settings-message" role="status">{msg}</p><button className="primary-button" disabled={saving}>{saving?"Saving…":"Save site controls"}</button></div></form>}
