ALTER TABLE "Report" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "Report" DROP CONSTRAINT IF EXISTS "Report_userId_fkey";
ALTER TABLE "Report" ADD CONSTRAINT "Report_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
